src/SolidFoundation.Feature.SiteDemo1/SiteDemo1/Models/SiteDemo1ContentBlocks.cs
using EPiServer.Core;
using SolidFoundation.Foundation.Foundation.Models.BaseModels;

namespace SolidFoundation.Feature.SiteDemo1.SiteDemo1.Models;

public interface ISiteDemo1ContentBlocks
{
}

src/SolidFoundation.Feature.SiteDemo1/SiteDemo1/Components/Footer/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SolidFoundation.Feature.SiteDemo1.SiteDemo1.Components.Footer.Services;

namespace SolidFoundation.Feature.SiteDemo1.SiteDemo1.Components.Footer;

public class FooterViewComponent : ViewComponent
{
    private readonly IFooterViewModelFactory _footerViewModelFactory;

    public FooterViewComponent(IFooterViewModelFactory footerViewModelFactory)
    {
        _footerViewModelFactory = footerViewModelFactory;
    }

    public IViewComponentResult Invoke()
    {
        var viewModel = _footerViewModelFactory.Create();
        return View("~/SiteDemo1/Components/Footer/Default.cshtml", viewModel);
    }
}

src/SolidFoundation.Feature.SiteDemo1/SiteDemo1/Components/MainNavigation/MainNavigationViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using EPiServer;
using EPiServer.Core;
using Microsoft.AspNetCore.Mvc;
using SolidFoundation.Feature.SiteDemo1.SiteDemo1.Pages.Home;
using SolidFoundation.Foundation.Foundation.Models.ViewModels;

namespace SolidFoundation.Feature.SiteDemo1.SiteDemo1.Components.MainNavigation;

public class MainNavigationViewComponent : ViewComponent
{
    private readonly IContentLoader _contentLoader;
    private readonly IContentLanguageAccessor _contentLanguageAccessor;

    public MainNavigationViewComponent(IContentLoader contentLoader, IContentLanguageAccessor contentLanguageAccessor)
    {
        _contentLoader = contentLoader;
        _contentLanguageAccessor = contentLanguageAccessor;
    }

    public IViewComponentResult Invoke(IContent currentContent)
    {
        var home = _contentLoader.Get<PageData>(ContentReference.StartPage);
        var children =
            _contentLoader.GetChildren<PageData>(ContentReference.StartPage, _contentLanguageAccessor.Language);

        var contentReferencesForNavigation = new List<PageData> { home };
        contentReferencesForNavigation.AddRange(children);
        return View("~/SiteDemo1/Components/MainNavigation/Default.cshtml", (NavigationItems: contentReferencesForNavigation, CurrentContentLink : currentContent.ContentLink));
    }
}

src/SolidFoundation.Feature.SiteDemo1/SiteDemo1/Pages/Article/ArticlePage.cshtml
@using EPiServer.Web.Mvc.Html
@model SolidFoundation.Foundation.Foundation.Models.ViewModels.IContentViewModel<SolidFoundation.Feature.SiteDemo1.SiteDemo1.Pages.Article.ArticlePage>

<div id="body">
    <div class="header">
        <div>
            <h1>@Html.PropertyFor(m => m.CurrentContent.PageHeadline)</h1>
        </div>
    </div>
    <div class="body">
        <img src="@Url.ContentUrl(Model.CurrentContent.HeroImage)" alt="Some Image">
    </div>
    <div class="footer">
        <div class="sidebar">
            <h2>@Html.PropertyFor(m => m.CurrentContent.SidebarHeadline)</h2>
            @Html.PropertyFor(m => m.CurrentContent.SidebarBody)
        </div>
        <div class="article">
            @Html.PropertyFor(m => m.CurrentContent.Body)
        </div>
    </div>
</div>

src/SolidFoundation.Feature.SiteDemo1/SiteDemo1/Pages/Home/HomePage.cshtml
@using EPiServer.Web.Mvc.Html
@model SolidFoundation.Foundation.Foundation.Models.ViewModels.IContentViewModel<SolidFoundation.Feature.SiteDemo1.SiteDemo1.Pages.Home.HomePage>

<div id="body" class="home">
	<div class="header">
		<img src="@Url.ContentUrl(Model.CurrentContent.HeroImage)" alt="">
		<div>
			<a href="@Url.ContentUrl(Model.CurrentContent.HeroPageLink)">@Html.PropertyFor(m => m.CurrentContent.HeroLinkText)</a>
		</div>
	</div>
	@Html.PropertyFor(m => m.CurrentContent.PageContent, new { HasContainer = false, HasItemContainers = false })
</div>

src/SolidFoundation.Feature.SiteDemo1/SiteDemo1/Pages/Products/ProductItemPage.cshtml
@using EPiServer.Web.Mvc.Html
@model SolidFoundation.Foundation.Foundation.Models.ViewModels.IContentViewModel<SolidFoundation.Feature.SiteDemo1.SiteDemo1.Pages.Products.ProductItemPage>

<div id="body">
    <div class="header">
        <div>
            <h1>@Html.PropertyFor(m => m.CurrentContent.ProductName)</h1>
        </div>
    </div>
    <div class="footer">
        <div class="productImage">
            <img src="@Url.ContentUrl(Model.CurrentContent.ProductImage)" alt="@Html.PropertyFor(m => m.CurrentContent.ProductDescription)">
        </div>        
        <div class="article">
            @Html.PropertyFor(m => m.CurrentContent.ProductDescription)
        </div>
    </div>
</div>

src/SolidFoundation.Feature.SiteDemo1/SiteDemo1/Pages/Products/ProductsPage.cshtml
@using SolidFoundation.Feature.SiteDemo1.SiteDemo1.Pages.Products.Services
@using EPiServer.Web.Mvc.Html
@model SolidFoundation.Foundation.Foundation.Models.ViewModels.IContentViewModel<SolidFoundation.Feature.SiteDemo1.SiteDemo1.Pages.Products.ProductsPage>

@inject IProductsPageViewModelFactory ViewModelFactory;

@{
    var viewModel = ViewModelFactory.Create(Model.CurrentContent);
}

<div id="body">
	<div class="header">
		<div>
			<h1>@Html.PropertyFor(m => m.CurrentContent.PageHeadline)</h1>
		</div>
	</div>
	<div>
		@foreach (var category in viewModel.Categories)
		{
			<ul>
				<li>
					<h1>@category.CategoryName</h1>
					<p>@category.KeySellingPoint</p>
				</li>
				@foreach (var productLink in category.ProductLinks)
				{
					<li>
						<a href="@productLink.Url">
							<img src="@productLink.ImageUrl" alt="@productLink.Name">
							<h2>@productLink.Name</h2>
						</a>
					</li>
				}
			</ul>
		}
	</div>
</div>

src/SolidFoundation.Feature.SiteDemo1/SiteDemo1/Views/Shared/_SiteLayout.cshtml
@model SolidFoundation.Foundation.Foundation.Models.ViewModels.IContentViewModel<EPiServer.Core.IContent>

@{
    Layout = "~/Foundation/Views/Shared/_MasterLayout.cshtml";
}
<div id="page">
	<div id="header">
		<div>
			<a href="/" class="logo"><img src="/_content/site-demo-1/images/logo.png" alt="Freeze"></a>
			<vc:main-navigation current-content="Model.CurrentContent"></vc:main-navigation>
		</div>
	</div>

	@RenderBody()
	<vc:footer></vc:footer>
</div>

@section HeaderSection
{
	<link rel="stylesheet" href="/_content/site-demo-1/css/style.css" type="text/css">
	<link rel="stylesheet" type="text/css" href="/_content/site-demo-1/css/mobile.css">
	<script src="/_content/site-demo-1/js/mobile.js" type="text/javascript"></script>	
}